# Generated by Django 2.2 on 2021-10-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('calorie', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=255)),
            ],
        ),
    ]
