# Generated by Django 3.2.9 on 2021-12-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='default_profile_img', upload_to='profile_img'),
        ),
    ]
