# Generated by Django 2.2 on 2021-10-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='price',
            new_name='img_path',
        ),
        migrations.AlterField(
            model_name='menu',
            name='calorie',
            field=models.IntegerField(),
        ),
    ]
