# Generated by Django 3.2.9 on 2021-12-04 06:33

from django.db import migrations, models
import foods.validators


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('place_link', models.URLField(validators=[foods.validators.validate_no_place_link])),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('image_1', models.ImageField(upload_to='food_img/')),
                ('image_2', models.ImageField(blank=True, upload_to='food_img/')),
                ('image_3', models.ImageField(blank=True, upload_to='food_img/')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용중인 닉네임입니다'}, max_length=20, null=True, unique=True, validators=[foods.validators.validate_no_special_characters]),
        ),
    ]
