# Generated by Django 3.2.9 on 2022-02-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_comment_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
