# Generated by Django 3.2.9 on 2021-11-19 11:06

import django.core.validators
from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211114_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(3, '음식의 설명이나 기분을 3글자 이상 적어주세요!'), posts.validators.validate_numbers]),
        ),
        migrations.AlterField(
            model_name='post',
            name='food_img',
            field=models.ImageField(upload_to='food_img'),
        ),
    ]
