# Generated by Django 3.2.9 on 2021-11-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211119_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='food_img',
            field=models.ImageField(upload_to='food_img/'),
        ),
    ]
