apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-django-deployment
  labels:
    app: kubernetes-django-food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-django-food
  template:
    metadata:
      labels:
        app: kubernetes-django-food
    spec:
      containers:
      - name: kubernetes-django-food
        image: hongreat/kubernetes-django-food:latest
        ports:
        - containerPort: 8000
      imagePullSecrets: 
        - name: regcred
